name: RustClippy CI

on: [push, pull_request]

jobs:
  clippy:
    name: Rust Clippy CI on ${{matrix.os}}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
